config/routes.rb
Catarse::Application.routes.draw do
  ActiveAdmin.routes(self)

  filter :locale

  root :to => "projects#index"
  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report

  match '/sitemap' => "static#sitemap", :as => :sitemap
  # Static Pages
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore/:quick" => "explore#index", :as => :explore_quick
  post '/explore/update_attribute_on_the_spot' => "explore#update_attribute_on_the_spot"
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  end
  resources :projects, :only => [:index, :new, :create, :show] do
    resources :rewards
    resources :backers, :controller => 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'comments'
      get 'updates'
    end
  end
  resources :users, :only => [:show] do
    post 'update_attribute_on_the_spot', :on => :collection
  end
  resources :credits, :only => [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end
  resources :comments, :only => [:index, :show, :create, :destroy]

  resources :paypal, :only => [] do
    member do
      get 'pay'
      get 'success'
      get 'cancel'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/:permalink" => "curated_pages#show", :as => :curated_page
end

app/controllers/credits_controller.rb
# coding: utf-8
class CreditsController < ApplicationController
  def index
    return unless require_login
    @title = t('credits.title')
    @refund_backs = current_user.backs.confirmed.can_refund.within_refund_deadline.order(:created_at).all
  end

  def refund
    return error(t('require_login')) unless current_user
    return error(t('credits.refund.refunded')) if backer.refunded
    return error(t('credits.refund.requested_refund')) if backer.requested_refund
    return error(t('credits.refund.cannot_refund')) unless backer.can_refund
    return error(t('credits.refund.no_credits')) unless current_user.credits >= backer.value

    backer.update_attribute :requested_refund, true
    current_user.update_attribute :credits, current_user.credits - backer.value
    current_user.reload

    CreditsMailer.request_refund_from(backer).deliver

    render :json => { :ok => true, :backer_id => backer.id, :credits => current_user.display_credits }
  rescue
    return error(t('credits.refund.error'))
  end

  private
    def error(message)
      render :json => { :ok => false,
                        :backer_id => backer.id,
                        :credits => (current_user.display_credits if current_user),
                        :message => message }
    end

    def backer
      @backer = Backer.find params[:backer_id]
    end
end

app/views/credits/index.html.haml
= content_for :content_header do
  %h1= t('.title')
  %h2= t('.subtitle')
#credits
  %h1= t('.current_credits_html', :credits => current_user.display_credits)
  -#buy_credits
    = t('.buy_credits_html')
    = form_tag(buy_credits_path, :method => :get) do
      %fieldset
        = submit_tag t('.buy_credits')
  - if @refund_backs.empty?
    %h2= t('.no_refunds')
  - else
    %h2= t('.refunds_title')
    %table
      %thead
        %tr
          %th= t('.project')
          %th= t('.created_at')
          %th= t('.value')
          %th= t('.refund_deadline')
          %th= t('.status')
      %tbody
        - @refund_backs.each do |back|
          %tr{ :id => back.id, :class => cycle("even", "odd") }
            %td= link_to back.project.name, project_path(back.project)
            %td= l back.created_at.to_date
            %td= back.display_value
            %td= l back.refund_deadline.to_date
            %td.status
              .text
                - if back.refunded
                  = t('.refunded')
                - elsif back.requested_refund
                  = t('.requested_refund')
                - else
                  = link_to t('.request_refund'), '#'
              .error.hide
              = image_tag "loading.gif", :class => 'loading hide'
    .important= t('.important_html')
:javascript
  var confirm_text = '#{t('.confirm')}'
= javascript_include_tag 'credits'