config/routes.rb
Catarse::Application.routes.draw do
  ActiveAdmin.routes(self)

  filter :locale

  root :to => "projects#index"
  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report

  match '/sitemap' => "static#sitemap", :as => :sitemap
  # Static Pages
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore/:quick" => "explore#index", :as => :explore_quick
  post '/explore/update_attribute_on_the_spot' => "explore#update_attribute_on_the_spot"
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  end
  resources :projects, :only => [:index, :new, :create, :show] do
    resources :rewards
    resources :backers, :controller => 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'comments'
      get 'updates'
    end
  end
  resources :users, :only => [:show] do
    post 'update_attribute_on_the_spot', :on => :collection
  end
  resources :credits, :only => [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end
  resources :comments, :only => [:index, :show, :create, :destroy]

  resources :paypal, :only => [] do
    member do
      get 'pay'
      get 'success'
      get 'cancel'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/:permalink" => "curated_pages#show", :as => :curated_page
end

app/models/backer.rb
# coding: utf-8
class Backer < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::DateHelper
  belongs_to :project
  belongs_to :user
  belongs_to :reward
  has_many :payment_logs
  has_one :payment_detail
  validates_presence_of :project, :user, :value
  validates_numericality_of :value, :greater_than_or_equal_to => 10.00
  validate :reward_must_be_from_project
  scope :anonymous, where(:anonymous => true)
  scope :not_anonymous, where(:anonymous => false)
  scope :confirmed, where(:confirmed => true)
  scope :not_confirmed, where(:confirmed => false)
  scope :pending, where(:confirmed => false)
  scope :display_notice, where(:display_notice => true)
  scope :can_refund, where(:can_refund => true)
  scope :within_refund_deadline, where("current_timestamp < (created_at + interval '180 days')")
  after_create :define_key, :define_payment_method
  def define_key
    self.update_attribute :key, Digest::MD5.new.update("#{self.id}###{self.created_at}###{Kernel.rand}").to_s
  end
  def define_payment_method
    self.update_attribute :payment_method, 'MoIP'
  end
  # after_save :update_user_credits
  # def update_user_credits
  #   self.user.update_credits
  # end
  before_save :confirm?
  def confirm?
    if confirmed and confirmed_at.nil?
      self.confirmed_at = Time.now
      self.display_notice = true
    end
  end
  def confirm!
    update_attribute :confirmed, true
    update_attribute :confirmed_at, Time.now
  end
  def reward_must_be_from_project
    return unless reward
    errors.add(:reward, I18n.t('backer.reward_must_be_from_project')) unless reward.project == project
  end
  validate :value_must_be_at_least_rewards_value
  def value_must_be_at_least_rewards_value
    return unless reward
    errors.add(:value, I18n.t('backer.value_must_be_at_least_rewards_value', :minimum_value => reward.display_minimum)) unless value >= reward.minimum_value
  end
  validate :should_not_back_if_maximum_backers_been_reached, :on => :create
  def should_not_back_if_maximum_backers_been_reached
    return unless reward and reward.maximum_backers and reward.maximum_backers > 0
    errors.add(:reward, I18n.t('backer.should_not_back_if_maximum_backers_been_reached')) unless reward.backers.confirmed.count < reward.maximum_backers
  end
  def display_value
    number_to_currency value, :unit => "R$", :precision => 0, :delimiter => '.'
  end
  def display_confirmed_at
    I18n.l(confirmed_at.to_date) if confirmed_at
  end
  def platform_fee(fee=7.5)
    (value.to_f * fee)/100
  end
  def display_platform_fee(fee=7.5)
    number_to_currency platform_fee(fee), :unit => "R$", :precision => 2, :delimiter => '.'
  end
  def payment_service_fee
    if payment_detail
      payment_detail.service_tax_amount.to_f
    else
      build_payment_detail.update_from_service
      payment_detail.service_tax_amount.to_f
    end
  end
  def moip_value
    "%0.0f" % (value * 100)
  end
  def generate_credits!
    return if self.can_refund
    self.user.update_attribute :credits, self.user.credits + self.value
    self.update_attribute :can_refund, true
  end
  def refund_deadline
    created_at + 180.days
  end
  def as_json(options={})

    json_attributes = {
      :id => id,
      :anonymous => anonymous,
      :confirmed => confirmed,
      :confirmed_at => display_confirmed_at,
      :user => user.as_json(options.merge(:anonymous => anonymous))
    }

    if options and options[:can_manage]
      json_attributes.merge!({
        :display_value => display_value,
        :reward => reward
      })
    end

    json_attributes

  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new
  before_filter :load_project

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").paginate :page => params[:page], :per_page => 10
    render :json => @backers.to_json(:can_manage => can?(:manage, @project))
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end
    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    @backer = @project.backers.new(params[:backer])

    unless @backer.save
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end

    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login

    backer = current_user.backs.find params[:id]
    if backer.credits
      if current_user.credits < backer.value
        flash[:failure] = t('projects.backers.checkout.no_credits')
        return redirect_to new_project_backer_path(backer.project)
      end
      unless backer.confirmed
        current_user.update_attribute :credits, current_user.credits - backer.value
        backer.update_attribute :payment_method, 'Credits'
        backer.confirm!
      end
      flash[:success] = t('projects.backers.checkout.success')
      redirect_to thank_you_path
    else
      begin
        current_user.update_attributes params[:user]
        current_user.reload
        payer = {
          :nome => current_user.full_name,
          :email => current_user.email,
          :logradouro => current_user.address_street,
          :numero => current_user.address_number,
          :complemento => current_user.address_complement,
          :bairro => current_user.address_neighbourhood,
          :cidade => current_user.address_city,
          :estado => current_user.address_state,
          :pais => "BRA",
          :cep => current_user.address_zip_code,
          :tel_fixo => current_user.phone_number
        }
        payment = {
          :valor => "%0.0f" % (backer.value),
          :id_proprio => backer.key,
          :razao => "Apoio para o projeto '#{backer.project.name}'",
          :forma => "BoletoBancario",
          :dias_expiracao => 2,
          :pagador => payer,
          :url_retorno => thank_you_url
        }
        response = MoIP::Client.checkout(payment)
        backer.update_attribute :payment_token, response["Token"]
        session[:_payment_token] = response["Token"]
        redirect_to MoIP::Client.moip_page(response["Token"])
      rescue
        flash[:failure] = t('projects.backers.checkout.moip_error')
        return redirect_to new_project_backer_path(backer.project)
      end
    end
  end



  private

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper
  inherit_resources
  actions :index, :show, :new, :create
  respond_to :html, :except => [:backers, :comments, :updates]
  respond_to :json, :only => [:show, :backers, :comments, :updates]
  can_edit_on_the_spot
  skip_before_filter :detect_locale, :only => [:backers, :comments, :updates]
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot
  before_filter :date_format_convert, :only => [:create]
  def date_format_convert
    # TODO localize here and on the datepicker on project_form.js
    params["project"]["expires_at"] = Date.strptime(params["project"]["expires_at"], '%d/%m/%Y')
  end

  def index
    index! do
      @title = t("site.title")
      @home_page = Project.includes(:user, :category).visible.home_page.limit(6).order('"order"').all
      @expiring = Project.includes(:user, :category).visible.expiring.not_home_page.not_expired.order('expires_at, created_at DESC').limit(3).all
      @recent = Project.includes(:user, :category).visible.not_home_page.not_expiring.not_expired.where("projects.user_id <> 7329").order('created_at DESC').limit(3).all
      @successful = Project.includes(:user, :category).visible.not_home_page.successful.order('expires_at DESC').limit(3).all
      @curated_pages = CuratedPage.visible.order("created_at desc").limit(6)
    end
  end
  def start
    @title = t('projects.start.title')
  end
  def send_mail
    current_user.update_attribute :email, params[:contact] if current_user.email.nil?
    ProjectsMailer.start_project_email(params[:about], params[:rewards], params[:links], params[:contact], current_user, "#{I18n.t('site.base_url')}#{user_path(current_user)}").deliver
    flash[:success] = t('projects.send_mail.success')
    redirect_to :root
  end
  def new
    return unless require_login
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end
  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    create!(:notice => t('projects.create.success'))
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attribute :short_url, bitly
    end
  end
  def show
    show!{
      @title = @project.name
      @rewards = @project.rewards.order(:minimum_value).all
      @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
      @updates = @project.updates.all
      @update = @project.comments.new :project_update => true
      @comments = @project.comments.all
      @comment = @project.comments.new
    }
  end
  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo
      render :json => project.vimeo.to_json
    else
      render :json => {:id => false}.to_json
    end
  end
  def cep
    address = BuscaEndereco.por_cep(params[:cep])
    render :json => {
      :ok => true,
      :street => "#{address[0]} #{address[1]}",
      :neighbourhood => address[2],
      :state => address[3],
      :city => address[4]
    }.to_json
  rescue
    render :json => {:ok => false}.to_json
  end

  def comments
    @project = Project.find params[:id]
    @comments = @project.comments.order("created_at DESC").paginate :page => params[:page], :per_page => 5
    respond_with @comments
  end

  def updates
    @project = Project.find params[:id]
    @updates = @project.updates.order("created_at DESC").paginate :page => params[:page], :per_page => 3
    respond_with @updates
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def pending
    return unless require_admin
    @title = t('projects.pending.title')
    @search = Project.search(params[:search])
    @projects = @search.order('projects.created_at DESC').paginate :page => params[:page]
  end
  def pending_backers
    return unless require_admin
    @title = t('projects.pending_backers.title')
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").paginate :page => params[:page]
    @total_backers = User.backers.count
    @total_backs = Backer.confirmed.count
    @total_backed = Backer.confirmed.sum(:value)
    @total_users = User.primary.count
  end
  private

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=diogob&apiKey=R_76ee3ab860d76d0d1c1c8e9cc5485ca1&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end
  def can_update_on_the_spot?
    project_fields = []
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "home_page", "order"]
    backer_fields = ["display_notice"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = []
    reward_admin_fields = ["description"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.id == project.user.id or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.admin
    end
  end
end

app/views/projects/backers/_anonymous_warning.en.html.slim
strong Are you sure you want your back to be anonymous? 
| Leaving your back public gives you a better reputation and count points on our ranking of backers.
br
br
| Besides that, the amount you backed will never be disclosed to no one but the project owner (who will always know who you are), even if your back is public.

app/views/projects/backers/_anonymous_warning.pt.html.slim
strong Você tem certeza que quer que seu apoio seja anônimo? 
| Deixar seu apoio público aumenta sua reputação e conta pontos para o nosso ranking de apoiadores.
br
br
| Além disso, o valor do seu apoio não será divulgado para ninguém além do dono do projeto (que sempre saberá quem você é), mesmo que seu apoio seja público.

app/views/projects/backers/_back_text.en.html.slim
h3 How do I back this project?
p First, chose the value and reward you wish. Then we will redirect you to #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} so you can proceed with the payment.
h3 When is the payment made and confirmed?
p Shortly after MoIP confirms the transaction. After that, if the project doesn't reach #{@project.display_goal} until #{@project.display_expires_at}, you will receive your money back as credits on Catarse.
h3 Oh, so I receive my money back if the project doesn't succeed?
p Yes! You receive 100% back as credits to back other projects on Catarse.
h3 What if I don't want to use the credits on Catarse?
p No problem. Just go to #{link_to t('credits.title'), credits_path, :target => :_blank}, up until 180 days after your payment, and request a refund. If you payed with credit card, the refund will be received in your next bill. If you payed with debit or transfer, the only way to receive the refund is to open an account on MoIP. This way we transfer you the value from our account to yours and, from there, you transfer to your bank account. No matter what way you chose, you wont have to pay anything.
h3 If the project is successful, how do I receive my reward?
p When your reward is ready, #{link_to @project.user.display_name, user_path(@project.user)} will get in touch with you to arrange the delivery.

app/views/projects/backers/_back_text.pt.html.slim
h3 Como eu apoio este projeto?
p Primeiro, escolha o valor e a recompensa desejados. Depois nós te redirecionaremos para o #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} para que você efetue o pagamento.
h3 Quando o pagamento é efetivado?
p Assim que o MoIP confirmar a transação. Depois, caso o projeto não atinja #{@project.display_goal} até #{@project.display_expires_at}, você receberá seu dinheiro de volta na forma de créditos no Catarse.
h3 Então eu recebo meu dinheiro de volta se o projeto não sair?
p Sim! Você recebe de volta 100% do que pagou na forma de créditos para apoiar outros projetos do Catarse.
h3 E se eu não quiser usar os créditos no Catarse?
p Sem problemas. É só entrar em #{link_to t('credits.title'), credits_path, :target => :_blank}, até 180 dias após seu apoio, e solicitar um estorno. Caso tenha pago com cartão de crédito, o estorno será feito na sua próxima fatura. Se pagou com débito em conta ou boleto bancário, a única maneira de fazer o estorno é você abrir uma conta no MoIP. Aí a gente transfere o valor da nossa conta para a sua e, de lá, você transfere para sua conta no banco. Independente do jeito que preferir, você não terá nenhuma despesa.
h3 Se o projeto for financiado, como eu recebo minha recompensa?
p Quando sua recompensa estiver pronta, #{link_to @project.user.display_name, user_path(@project.user)} vai entrar em contato com você para combinar a entrega.

app/views/projects/backers/new.html.haml
= content_for :content_header do
  %h1= t('.header.title')
  %h2= t('.header.subtitle')
#back_options
  = semantic_form_for @backer, :url => review_project_backers_path(@project), :html => { :id => 'backer_form' } do |form|
    = form.inputs do
      = hidden_field_tag 'credits', ("%0.0f" % current_user.credits)
      = form.input :value, :required => false
      - if current_user.credits >= 10
        = form.input :credits, :hint => t('formtastic.hints.backer.credits', :credits => current_user.display_credits)
      - @rewards[0].id = 0
      %script
        var rewards = new Array()
        - @rewards.each do |reward|
          rewards[#{reward.id || 0}] = #{reward.minimum_value}
      = form.input :reward, :as => :radio, :collection => @rewards
      = form.input :anonymous
      #anonymous_warning.important.hide= render 'anonymous_warning'
    = form.buttons do
      = form.commit_button t('.submit'), :button_html => {:disabled => true}
#back_info
  = image_tag @project.display_image
  #project_info
    .project_name= link_to @project.name, project_path(@project)
    .project_owner por #{link_to @project.user.display_name, user_path(@project.user)}
    .project_expires_at #{@project.time_to_go[:time]} #{@project.time_to_go[:unit]} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
  .clear
  = render 'back_text'
.clear
= javascript_include_tag 'back_project'

app/views/projects/backers/review.html.haml
= content_for :content_header do
  %h1= t('.title')
  %h2= t('.subtitle')
#project_review
  = image_tag @project.display_image, :id => 'project_image'
  %h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
  .clear
  #review_text
    - if @backer.reward
      = t('.review_with_reward_html', :value => @backer.display_value, :reward => @backer.reward.description)
    - else
      = t('.review_without_reward_html', :value => @backer.display_value)
  - if @backer.credits
    #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
  - else
    #international_payment
      %h1
        = t('.international.title')
        %a#international_link{ :href => '#' }
          = t('click_here')
      #international_expanded.hide
        %h1= t('.international.description')
        .international_important= t('.international.important_html')
        = form_tag(pay_paypal_path(@backer), :method => :get) do
          %fieldset
            = check_box_tag 'accept_international'
            = label_tag 'accept_international', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
          %fieldset
            = submit_tag t('.international.submit'), :disabled => true, :id => 'international_submit'
  = semantic_form_for current_user, :url => checkout_project_backer_path(@backer.project, @backer), :html => { :id => 'review_form' } do |form|
    = hidden_field_tag 'backer_id', @backer.id
    = hidden_field_tag 'backer_credits', @backer.credits
    - unless @backer.credits
      = form.inputs do
        = form.input :full_name, :required => true, :as => :string
        = form.input :cpf, :required => true, :as => :string, :input_html => {:autocomplete => 'off'}
        = form.input :email, :required => true, :as => :string
        = form.input :address_zip_code, :required => true, :as => :string, :input_html => {:autocomplete => 'off'}
        = form.input :address_street, :required => true, :as => :string
        = form.input :address_number, :required => true, :as => :string
        = form.input :address_complement, :required => false, :as => :string
        = form.input :address_neighbourhood, :required => true, :as => :string
        = form.input :address_city, :required => true, :as => :string
        = form.input :address_state, :required => true, :as => :select, :collection => State.array
        = form.input :phone_number, :required => true, :as => :string, :input_html => {:autocomplete => 'off'}
    .submit
      %fieldset
        = check_box_tag 'accept'
        = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
      = form.buttons do
        = form.commit_button (@backer.credits ? t('.submit.credits') : t('.submit.moip')), :button_html => {:disabled => true}
= javascript_include_tag 'jquery.maskedinput-1.2.2.min'
= javascript_include_tag 'jquery.cpf'
= javascript_include_tag 'review'