config/routes.rb
Catarse::Application.routes.draw do
  ActiveAdmin.routes(self)

  filter :locale

  root :to => "projects#index"
  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report

  match '/sitemap' => "static#sitemap", :as => :sitemap
  # Static Pages
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore/:quick" => "explore#index", :as => :explore_quick
  post '/explore/update_attribute_on_the_spot' => "explore#update_attribute_on_the_spot"
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  end
  resources :projects, :only => [:index, :new, :create, :show] do
    resources :rewards
    resources :backers, :controller => 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'comments'
      get 'updates'
    end
  end
  resources :users, :only => [:show] do
    post 'update_attribute_on_the_spot', :on => :collection
  end
  resources :credits, :only => [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end
  resources :comments, :only => [:index, :show, :create, :destroy]

  resources :paypal, :only => [] do
    member do
      get 'pay'
      get 'success'
      get 'cancel'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/:permalink" => "curated_pages#show", :as => :curated_page
end

app/views/layouts/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5421030-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_flash.html.haml
.flash{ :style => 'display:none' }
  - for key,msg in flash
    %div{ :class => "#{key} wrapper" }
      %div{ :class => key }= raw msg
= javascript_include_tag 'flash'

app/views/layouts/_footer.html.haml
#footer_menu
  %ul
    %li= link_to t('.guidelines'), guidelines_path
    %li= link_to t('.faq'), faq_path
    %li= link_to t('.terms'), terms_path
    %li= link_to t('.privacy'), privacy_path
    %li= mail_to t('site.email.contact'), t('.email')
#social_menu
  %ul
    %li
      = link_to "http://twitter.com/#{t('site.twitter')}", :target => :_blank do
        = image_tag('social/twitter_32.png', :title => "Twitter")
        = t('.twitter')
    %li
      = link_to t('site.facebook'), :target => :_blank do
        = image_tag('social/facebook_32.png', :title => "Facebook")
        = t('.facebook')
    %li
      = link_to t('site.blog'), :target => :_blank do
        = image_tag('social/rss_32.png', :title => "Blog")
        = t('.blog')
#colophon
  = link_to '', "http://comum.cc", :target => :_blank, :id => "grupo_comum_login"
  = link_to '', "http://powertothecrowd.com", :target => :_blank, :id => "power_to_the_crowd"

app/views/layouts/_head.html.haml
%head
  %meta{:charset => 'utf-8'}
  %meta{:name => "robots", :content => "index, follow"}
  %meta{:name => "author", :content => "Softa"}
  = yield :meta_tags
  %title
    - if @title
      == #{@title}#{' · ' if @title}#{t('site.name')}
    - else
      == #{yield :title} · #{t('site.name')}

  = stylesheet_link_tag 'le-frog/jquery-ui-1.8.6.custom.css', :media => 'screen, projection'
  = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
  /[if lt IE 9]
    = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"
  = javascript_include_tag 'jquery-1.4.4.min', 'jquery-ui-1.8.6.custom.min', 'jquery.ui.datepicker-pt-BR', 'jquery.numeric', 'jquery.maxlength', 'jquery.timers-1.2', 'timedKeyup', 'underscore-min', 'backbone-min', 'mustache', 'waypoints.min', 'jquery.jeditable.mini','on_the_spot'
  = javascript_include_tag 'jquery.scrollto'
  = csrf_meta_tag
  %link{ :rel => 'shortcut icon', :href => "/images/favicon.ico" }
  = render '/layouts/analytics'
  = render "/layouts/uservoice"

app/views/layouts/_locales.html.slim
#locales class=("notify" if flash[:locale])
  ul
    - I18n.available_locales.map(&:to_s).sort.each do |locale|
      li
        = link_to replace_locale(locale) do
          = image_tag "locales/#{locale}.png"

app/views/layouts/_login.html.haml
#login_overlay.overlay.hide
  #login.hide
    %a.close{ :href => '#' } X
    %h1= t('.title')
    = form_tag(auth_path) do
      = hidden_field_tag 'provider'
      = hidden_field_tag 'return_to'
      = link_to image_tag('auth/google_128.png', :title => 'Google'), 'google', :class => 'provider'
      = link_to image_tag('auth/orkut_128.png', :title => 'Orkut'), 'google', :class => 'provider'
      - OauthProvider.order('"order"').all.each do |p|
        = link_to image_tag("auth/#{p.path}_128.png", :title => p.name), p.path, :class => 'provider'
      %fieldset
        = check_box_tag 'remember_me', "1", true
        = label_tag 'remember_me', t('.remember_me'), :class => 'inline'
    %p= t('.description_html')
    %p= t('.tips_html')
= javascript_include_tag 'login'

app/views/layouts/_pre_header.html.haml
- if current_user and (not current_user.backs.display_notice.empty? or not current_user.notifications.not_dismissed.empty?)
  #pre_header
    - current_user.backs.display_notice.each do |back|
      %div{:id => "back_notice_#{back.id}", :class => "back_notice"}

        = t('.back_notice_html', :link => link_to(truncate(back.project.name, :length => 32), project_path(back.project)))
        &nbsp;
        %a.close{ :href => '#' } X
        = link_to "http://www.facebook.com/share.php?u=#{project_url(back.project)}", :target => :_blank do
          = image_tag 'auth/facebook_64.png', :title => 'Facebook', :class => 'social'
        = link_to "http://twitter.com/?status=#{t('i_backed', :name => back.project.name)} #{back.project.short_url}", :target => :_blank do
          = image_tag 'auth/twitter_64.png', :title => 'Twitter', :class => 'social'
    = javascript_include_tag 'back_notices'
    - current_user.notifications.not_dismissed.order(:created_at).each do |notification|
      %div{:id => "notification_#{notification.id}", :class => "notification"}
        = notification.text.html_safe
        &nbsp;
        %a.close{ :href => '#' } X
        - if notification.facebook_text
          = link_to "http://www.facebook.com/share.php?u=#{(notification.project ? project_url(notification.project) : root_url)}&t=#{notification.facebook_text}&v=4", :target => :_blank do
            = image_tag 'auth/facebook_64.png', :title => 'Facebook', :class => 'social'
        - if notification.twitter_text
          = link_to "http://twitter.com/?status=#{notification.twitter_text}", :target => :_blank do
            = image_tag 'auth/twitter_64.png', :title => 'Twitter', :class => 'social'
    = javascript_include_tag 'notifications'
- else
  #pre_header 
    = t('.content_html', :link => link_to( t('.help_link'),  "#{t('site.blog')}post/2826297563/passo-a-passo-apoiar-projetos", :target => :_blank))

app/views/layouts/_user.html.haml
#user
  = link_to '#', :id => 'user_menu_link' do
    = image_tag current_user.display_image, :id => 'display_image'
    = truncate current_user.display_name, :length => 24
    = image_tag 'dropdown.png', :class => 'dropdown'
  #user_menu.hide
    %ul
      %li= link_to t('.my_profile'), user_path(current_user)
      %li
        = link_to credits_path do
          = t('.my_credits')
          .small (#{current_user.display_credits})
      %li= link_to t('.logout'), logout_path
= javascript_include_tag 'user'

app/views/layouts/_uservoice.html.haml
:javascript
  var uservoiceOptions = {
    key: 'catarse',
    host: 'catarse.uservoice.com',
    forum: '103171',
    alignment: 'left',
    background_color:'#006600',
    text_color: 'white',
    hover_color: '#009900',
    lang: 'pt_BR',
    showTab: true
  };
  function _loadUserVoice() {
    var s = document.createElement('script');
    s.src = ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js";
    document.getElementsByTagName('head')[0].appendChild(s);
  }
  _loadSuper = window.onload;
  window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };

app/views/layouts/application.html.haml
!!! 5
%html{:lang => I18n.locale}
  = render :partial => 'layouts/head'
  %body#platform
    = render :partial => 'layouts/flash', :locals => { :flash => flash } unless flash.empty?
    = render :partial => 'layouts/locales'
    = render :partial => 'layouts/pre_header'
    #main
      #header_wrapper
        #header
          %h1{:class=>"#{align_logo_when_home}"}
            = link_to root_path do
              = image_tag "logo.png", :title => t('site.name')
          = render '/layouts/user' if current_user
          #menu
            %ul
              %li= link_to t('.menu.explore'), explore_path
              %li= link_to t('.menu.submit'), guidelines_path, :id => 'new_project_link'
              - unless current_user
                %li= link_to t('.menu.signup'), '#', :id => 'signup_link'
                %li= link_to t('.menu.login'), '#', :id => 'login_link'
          .clear
      #content_wrapper
        #content_header_wrapper
          #content_header
            = yield :content_header
        - if is_homepage?
          #notification_wrapper
            %div
              %h1= raw(t('.notifications.new_curated_pages'))
        #content
          = yield
      #footer= render :partial => "layouts/footer"
    = render '/layouts/login' unless current_user

app/views/layouts/embed.html.haml
!!! 5
%html{:lang => :pt}
  %head
    %meta{:charset => 'utf-8'}
    %title= "#{@title}#{' · ' if @title}#{t('site.name')}"
    = stylesheet_link_tag 'le-frog/jquery-ui-1.8.6.custom.css', :media => 'screen, projection'
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    /[if lt IE 9]
      = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"
    = javascript_include_tag 'jquery-1.4.4.min', 'jquery-ui-1.8.6.custom.min', 'jquery.ui.datepicker-pt-BR', 'jquery.numeric', 'jquery.maxlength', 'jquery.timers-1.2', 'timedKeyup'
    = csrf_meta_tag
    %link{ :rel => 'shortcut icon', :href => "/images/favicon.ico" }
    = render '/layouts/analytics'
  %body#platform
    = yield